### PR TITLE
Feature mma 461

### PR DESCRIPTION
**Pull request by holiday-sunrise**

### CODE REVIEW

**Review by mlischetti — CHANGES_REQUESTED** [review]
Can you please isolate the core changes involved in this issue? (Parent.java and PomModel.java changes should be removed from this PR)
Also can you provide a unit test? This test will clarify the issue and also probe that everything works ok after this changes. Additionally this test will be prevent us from regression bugs.

**Comment by holiday-sunrise** [comment]
Parent.java and PomModel.java changes are removed from this PR

**Comment by holiday-sunrise** [comment]
sorry my mistake

**Comment by mlischetti** [comment]
Hi @holiday-sunrise,
Please, can you please include a unit test? 
This test allows us to increase coverage and no future changes break the scenario.
Thanks

**Comment by holiday-sunrise** [comment]
now ok ?

**Review by mlischetti — APPROVED** [review]

**Pull request merged**
