### PR TITLE
Feature mma 462

### PR DESCRIPTION
**Pull request by holiday-sunrise**

### CODE REVIEW

**Review by mlischetti — CHANGES_REQUESTED** [review]
Can you please isolate the core changes involved in this issue? (Parent.java and PomModel.java are should be removed from this PR)
Also can you provide a unit test? This test will clarify the issue and also probe that everything works ok after this changes. Additionally this test will be prevent us from regression bugs.

**Comment by holiday-sunrise** [comment]
removed as requested

**Comment by mlischetti** [comment]
Hi, @holiday-sunrise can please you add a unit test? Thanks

**Comment by holiday-sunrise** [comment]
anything else to do

**Comment by holiday-sunrise** [comment]
any news ?

**Comment by mlischetti** [comment]
Hi @holiday-sunrise,
Have you been able to read my previous comment?
The last change that we need is that you rename the test method by _executeWithSchemaLocationAttributeIsNull_ (without _)
Thanks

**Comment by mlischetti** [comment]
@holiday-sunrise I'm so sorry, I forgot to send my review yesterday.
The only change needed in this PR is that rename the test method by executeWithSchemaLocationAttributeIsNull
Thanks

**Review by mlischetti — APPROVED** [review]

**Pull request merged**
